/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author PC
 */
public class Gui_ThongKeLuotVe extends javax.swing.JPanel {

    /**
     * Creates new form Gui_ThongKeLuotVe
     */
    public Gui_ThongKeLuotVe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pnlBieuDoHanhKhach = new javax.swing.JPanel();
        pnlChuyenDiNhieuNhat = new javax.swing.JPanel();
        scrollChuyenDi = new javax.swing.JScrollPane();
        tblChuyenDiNhieuNhat = new javax.swing.JTable();
        pnlLoc = new javax.swing.JPanel();
        lblThang = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        spNam = new javax.swing.JSpinner();
        cbThang = new javax.swing.JComboBox<>();
        pnlSoLuong = new javax.swing.JPanel();
        lblTongLuongKhach = new javax.swing.JLabel();
        lblTongSoVeDat = new javax.swing.JLabel();
        lblTongSoChuyen = new javax.swing.JLabel();
        txtTongLuongKhach = new javax.swing.JTextField();
        txtTongSoVeDat = new javax.swing.JTextField();
        txtTongSoChuyen = new javax.swing.JTextField();
        pnlBieuDoTyLe = new javax.swing.JPanel();

        setBackground(new java.awt.Color(234, 243, 251));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thống Kê Lượng Vé");

        pnlBieuDoHanhKhach.setBackground(new java.awt.Color(255, 255, 255));
        pnlBieuDoHanhKhach.setBorder(javax.swing.BorderFactory.createTitledBorder("Biểu đồ tỷ lệ hành khách"));

        javax.swing.GroupLayout pnlBieuDoHanhKhachLayout = new javax.swing.GroupLayout(pnlBieuDoHanhKhach);
        pnlBieuDoHanhKhach.setLayout(pnlBieuDoHanhKhachLayout);
        pnlBieuDoHanhKhachLayout.setHorizontalGroup(
            pnlBieuDoHanhKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        pnlBieuDoHanhKhachLayout.setVerticalGroup(
            pnlBieuDoHanhKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlChuyenDiNhieuNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlChuyenDiNhieuNhat.setBorder(javax.swing.BorderFactory.createTitledBorder("Chuyến đi nhiều nhất trong tháng"));

        tblChuyenDiNhieuNhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chuyến", "Số lượt đi"
            }
        ));
        scrollChuyenDi.setViewportView(tblChuyenDiNhieuNhat);

        javax.swing.GroupLayout pnlChuyenDiNhieuNhatLayout = new javax.swing.GroupLayout(pnlChuyenDiNhieuNhat);
        pnlChuyenDiNhieuNhat.setLayout(pnlChuyenDiNhieuNhatLayout);
        pnlChuyenDiNhieuNhatLayout.setHorizontalGroup(
            pnlChuyenDiNhieuNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollChuyenDi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        pnlChuyenDiNhieuNhatLayout.setVerticalGroup(
            pnlChuyenDiNhieuNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChuyenDiNhieuNhatLayout.createSequentialGroup()
                .addComponent(scrollChuyenDi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc"));

        lblThang.setText("Tháng:");

        lblNam.setText("Năm:");

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout pnlLocLayout = new javax.swing.GroupLayout(pnlLoc);
        pnlLoc.setLayout(pnlLocLayout);
        pnlLocLayout.setHorizontalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spNam, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlLocLayout.setVerticalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThang)
                    .addComponent(lblNam)
                    .addComponent(spNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlSoLuong.setBackground(new java.awt.Color(255, 255, 255));
        pnlSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder("Số lượng"));

        lblTongLuongKhach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongLuongKhach.setText("Tổng lượng khách:");

        lblTongSoVeDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongSoVeDat.setText("Tổng số vé đã đặt:");

        lblTongSoChuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongSoChuyen.setText("Tổng số chuyến:");

        txtTongSoVeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongSoVeDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSoLuongLayout = new javax.swing.GroupLayout(pnlSoLuong);
        pnlSoLuong.setLayout(pnlSoLuongLayout);
        pnlSoLuongLayout.setHorizontalGroup(
            pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoLuongLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongSoChuyen)
                    .addComponent(lblTongSoVeDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongLuongKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTongSoVeDat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongLuongKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongSoChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSoLuongLayout.setVerticalGroup(
            pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoLuongLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongLuongKhach)
                    .addComponent(txtTongLuongKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongSoVeDat)
                    .addComponent(txtTongSoVeDat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongSoChuyen)
                    .addComponent(txtTongSoChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pnlBieuDoTyLe.setBackground(new java.awt.Color(255, 255, 255));
        pnlBieuDoTyLe.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống kê lượt vé trong tháng"));

        javax.swing.GroupLayout pnlBieuDoTyLeLayout = new javax.swing.GroupLayout(pnlBieuDoTyLe);
        pnlBieuDoTyLe.setLayout(pnlBieuDoTyLeLayout);
        pnlBieuDoTyLeLayout.setHorizontalGroup(
            pnlBieuDoTyLeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBieuDoTyLeLayout.setVerticalGroup(
            pnlBieuDoTyLeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBieuDoTyLe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChuyenDiNhieuNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBieuDoHanhKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlBieuDoHanhKhach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChuyenDiNhieuNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBieuDoTyLe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongSoVeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongSoVeDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongSoVeDatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongLuongKhach;
    private javax.swing.JLabel lblTongSoChuyen;
    private javax.swing.JLabel lblTongSoVeDat;
    private javax.swing.JPanel pnlBieuDoHanhKhach;
    private javax.swing.JPanel pnlBieuDoTyLe;
    private javax.swing.JPanel pnlChuyenDiNhieuNhat;
    private javax.swing.JPanel pnlLoc;
    private javax.swing.JPanel pnlSoLuong;
    private javax.swing.JScrollPane scrollChuyenDi;
    private javax.swing.JSpinner spNam;
    private javax.swing.JTable tblChuyenDiNhieuNhat;
    private javax.swing.JTextField txtTongLuongKhach;
    private javax.swing.JTextField txtTongSoChuyen;
    private javax.swing.JTextField txtTongSoVeDat;
    // End of variables declaration//GEN-END:variables
}
