/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author PC
 */
public class Gui_ThongKeDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form Gui_ThongKeDoanhThu
     */
    public Gui_ThongKeDoanhThu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        scrollHoaDon = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        pnlLoc = new javax.swing.JPanel();
        lblThang = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        spNam = new javax.swing.JSpinner();
        cbThang = new javax.swing.JComboBox<>();
        pnlThongTinChiTiet = new javax.swing.JPanel();
        lblDoanhThuThang = new javax.swing.JLabel();
        lblSoHoaDonThang = new javax.swing.JLabel();
        lblSoHoaDonTra = new javax.swing.JLabel();
        lblSoVeTra = new javax.swing.JLabel();
        txtDoanhThuThang = new javax.swing.JTextField();
        txtSoHoaDonThang = new javax.swing.JTextField();
        txtSoHoaDonTra = new javax.swing.JTextField();
        txtSoVeTra = new javax.swing.JTextField();
        pnlDoanhThuNgay = new javax.swing.JPanel();

        setBackground(new java.awt.Color(234, 243, 251));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thống Kê Doanh Thu");

        pnlHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Ngày tạo", "Giờ tạo", "Tổng tiền"
            }
        ));
        scrollHoaDon.setViewportView(tblHoaDon);

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHoaDon, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addComponent(scrollHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc"));

        lblThang.setText("Tháng:");

        lblNam.setText("Năm:");

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));

        javax.swing.GroupLayout pnlLocLayout = new javax.swing.GroupLayout(pnlLoc);
        pnlLoc.setLayout(pnlLocLayout);
        pnlLocLayout.setHorizontalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(lblNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spNam, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLocLayout.setVerticalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThang)
                    .addComponent(lblNam)
                    .addComponent(spNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlThongTinChiTiet.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết"));

        lblDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDoanhThuThang.setText("Doanh thu trong tháng");

        lblSoHoaDonThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoHoaDonThang.setText("Số hóa đơn trong tháng");

        lblSoHoaDonTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoHoaDonTra.setText("Số hóa đơn trả");

        lblSoVeTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoVeTra.setText("Số vé trả");

        txtDoanhThuThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuThangActionPerformed(evt);
            }
        });

        txtSoHoaDonThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoHoaDonThangActionPerformed(evt);
            }
        });

        txtSoHoaDonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoHoaDonTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinChiTietLayout = new javax.swing.GroupLayout(pnlThongTinChiTiet);
        pnlThongTinChiTiet.setLayout(pnlThongTinChiTietLayout);
        pnlThongTinChiTietLayout.setHorizontalGroup(
            pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                        .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                                .addComponent(lblDoanhThuThang)
                                .addGap(71, 71, 71))
                            .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                                .addComponent(txtDoanhThuThang)
                                .addGap(49, 49, 49)))
                        .addGap(30, 30, 30)
                        .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoHoaDonThang)
                            .addComponent(txtSoHoaDonThang, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                        .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoHoaDonTra)
                            .addComponent(txtSoHoaDonTra, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoVeTra)
                            .addComponent(txtSoVeTra))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlThongTinChiTietLayout.setVerticalGroup(
            pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinChiTietLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoanhThuThang)
                    .addComponent(lblSoHoaDonThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoHoaDonThang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoHoaDonTra)
                    .addComponent(lblSoVeTra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoHoaDonTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoVeTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlDoanhThuNgay.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoanhThuNgay.setBorder(javax.swing.BorderFactory.createTitledBorder("Doanh thu các ngày trong tháng"));

        javax.swing.GroupLayout pnlDoanhThuNgayLayout = new javax.swing.GroupLayout(pnlDoanhThuNgay);
        pnlDoanhThuNgay.setLayout(pnlDoanhThuNgayLayout);
        pnlDoanhThuNgayLayout.setHorizontalGroup(
            pnlDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDoanhThuNgayLayout.setVerticalGroup(
            pnlDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlThongTinChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlDoanhThuNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlThongTinChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDoanhThuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoHoaDonThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoHoaDonThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoHoaDonThangActionPerformed

    private void txtDoanhThuThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuThangActionPerformed

    private void txtSoHoaDonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoHoaDonTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoHoaDonTraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JLabel lblDoanhThuThang;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblSoHoaDonThang;
    private javax.swing.JLabel lblSoHoaDonTra;
    private javax.swing.JLabel lblSoVeTra;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlDoanhThuNgay;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlLoc;
    private javax.swing.JPanel pnlThongTinChiTiet;
    private javax.swing.JScrollPane scrollHoaDon;
    private javax.swing.JSpinner spNam;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDoanhThuThang;
    private javax.swing.JTextField txtSoHoaDonThang;
    private javax.swing.JTextField txtSoHoaDonTra;
    private javax.swing.JTextField txtSoVeTra;
    // End of variables declaration//GEN-END:variables
}
