/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package compoment;

/**
 *
 * @author PC
 */
public class TauIteam extends javax.swing.JPanel {

    /**
     * Creates new form TauIteam
     */
    public TauIteam() {
        initComponents();
    }
    
    /**
     * Set dữ liệu cho TauIteam
     */
    public void setData(String tenTau, String thoiGianDi, String thoiGianDen) {
        lbTen.setText(tenTau);
        lbifTGDi.setText(thoiGianDi);
        lbifTGDen.setText(thoiGianDen);
    }
    
    /**
     * Set màu nền khi được chọn
     */
    public void setSelected(boolean selected) {
        if (selected) {
            jPanel1.setBackground(new java.awt.Color(91, 192, 235)); // Màu xanh
        } else {
            jPanel1.setBackground(new java.awt.Color(240, 240, 240)); // Màu xám nhạt
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIcon = new javax.swing.JLabel();
        lbDi = new javax.swing.JLabel();
        lbDen = new javax.swing.JLabel();
        lbifTGDi = new javax.swing.JLabel();
        lbifTGDen = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/train.png"))); // NOI18N

        lbDi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbDi.setText("TG đi");

        lbDen.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbDen.setText("TG đến");

        lbifTGDi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbifTGDi.setText("08/04/2024 08:30");

        lbifTGDen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbifTGDen.setText("08/04/2024 09:15");

        lbTen.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        lbTen.setText("SE10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbifTGDen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDi)
                        .addGap(22, 22, 22)
                        .addComponent(lbifTGDi)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTen)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDi)
                    .addComponent(lbifTGDi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDen)
                    .addComponent(lbifTGDen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDen;
    private javax.swing.JLabel lbDi;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbifTGDen;
    private javax.swing.JLabel lbifTGDi;
    // End of variables declaration//GEN-END:variables
}
