/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package compoment;

/**
 *
 * @author PC
 */
public class ToaIteam extends javax.swing.JPanel {

    /**
     * Creates new form ToaIteam
     */
    public ToaIteam() {
        initComponents();
    }
    
    /**
     * Set số toa
     */
    public void setSoToa(int soToa) {
        lbViTri.setText(String.valueOf(soToa));
    }
    
    /**
     * Set màu nền khi được chọn
     */
    public void setSelected(boolean selected) {
        if (selected) {
            setBackground(new java.awt.Color(144, 238, 144)); // Xanh lá nhạt
        } else {
            setBackground(java.awt.Color.WHITE); // Màu trắng
        }
    }
    
    /**
     * Set màu hover
     */
    public void setHover(boolean hover) {
        if (!getBackground().equals(new java.awt.Color(144, 238, 144))) {
            if (hover) {
                setBackground(new java.awt.Color(245, 245, 245)); // Xám nhạt
            } else {
                setBackground(java.awt.Color.WHITE); // Màu trắng
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIconToa = new javax.swing.JLabel();
        lbViTri = new javax.swing.JLabel();

        lbIconToa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/carriage.png"))); // NOI18N

        lbViTri.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbViTri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbViTri.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbViTri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIconToa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbIconToa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbViTri))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIconToa;
    private javax.swing.JLabel lbViTri;
    // End of variables declaration//GEN-END:variables
}
